---
  el:
    hosts:
      centos7:
        ansible_connection: docker
  deb:
    hosts:
      centos8:
        ansible_connection: docker
     
  locals:
    hosts:
      local:
        ansible_connection: ansible.builtin.local
